/*************Reset Variables at time of checklist Creation*********************/
function intialize_1(){
	$("#collapseForQuestion").removeClass("expanded").addClass("notExpanded");
	$("#collapseForAnswer").removeClass("expanded").addClass("notExpanded");
	$("#collapseForForms").removeClass("expanded").addClass("notExpanded");
	$("#collapseForCustomized").removeClass("expanded").addClass("notExpanded");
	$("#collapseOne").removeClass("expanded").addClass("notExpanded");
	ruleOrder=0;
	editFormFLag=0;
	maxLenVal=""; 
	regCheck="";
	num=0;
	number=0;
	deleteFormImageFlag=0;
	deleteSectionImageFlag=0;
	deleteFormImage=[];
	deleteSectionImage=[];
	deleteStepImage=[];
	deleteStepImageFlag=0;
	deleteQuesImage=[];
	deleteQuesImageFlag=0;
	seqNoFormImages = 0;
	seqNoSectionImages =0;
	seqNoStepImages=0;
	seqNoQuestionImages=0;
	labelEditFormFlag=0;
	labelEditSectionArr=[];
	labelEditStepArr=[];
	labelEditQuesArr=[];
	quesCountNumber_=0;
	sect_Count=0
	countSect=0;
	stepCount_=0;
	quesOrderNo=[];
	innerFlagEdit = 0;
	textAreacount = 0;
	imageUploadCount = 0;
	dropDownCount = 0;
	datePickerCount = 0;
	buttonCount = 0;
	radioButton = 0;
	checkBoxCount = 0;
	commentCount = 0;
	signatureCount = 0;
	labelCount = 0;
	textBoxCount = 0;
	quesText = 0;
	addIm=0;
	ID_num=0;
	editFlag = 0;
	rule_name;
	formula_;
	formula_data;
	recentele;
	adActionarra =[];
	secArr = [];
	stepArr =[];
	quesArr = [];
	formArr = [];
	textAreaJsonArr =[];
	imageUploadJsonArr =[];
	datePickerJsonArr = [];
	buttonJsonArr =[];
	checkBoxJsonArr = [];
	radioButtonJsonArr =[];
	dropDownJsonArr = [];
	textBoxJsonArr =[];
	labelJsonArr = [];
	signatureJsonArr = [];
	ruleMainArr = [];
	rulePropArr=[];
	ruleRadioArr=[];
	ruleChkArr=[];
	textCountArr =[];
	dropCountArr = [];
	dateCountArr = [];
	btnCountArr = [];
	radioCountArr =[];
	checkCountArr = [];
	commentCountArr = [];
	textBoxCountArr = [];
	sigCountArr = [];
	labelCountArr = [];
	addimCountArr = [];
	imuploadCountArr = [];
	flagEle = 0;
	flag = 0;
	countForImages=0;
	ID_num = 0;
	ele;
	element;
	validateFlag=0;
	validateFlag_=0;
	validateFlag1=0;
	validateFlagChk=0;
	ElementNo="";
	clickedRow="";
	desc="";
	tag="";
	actionID_num="";
	action="";
	tagValue="";
	opVal="";
	fields="";
	output="";
	innerID = 0;
	actionRulesArr =[];
	uploadFormFlag=0;
	seqNoFormImages = 0;
}
/*************Reset Variables at time of Editing Checklist*********************/
function intialize(){
	countOFText=0;
	countOFDrop=0;
	countOFBtn=0;
	countOFDate=0;
	countOFRadio=0;
	countOFCheck=0;
	countOFTBox=0;
	countOFLabel=0;
	countOFSig=0;
	countOFIm=0;
	countOFAi=0;
	quesFlag=0;
	ansFlag=0;
	sectionNameFlag=0;
	stepNameFlag=0;
	quesTextAreaFlag = 0;
	quesTextAreaCompulsoryFlag=0;

}
function editCall(){
	$("#collapseForQuestion").removeClass("expanded").addClass("notExpanded");
	$("#collapseForAnswer").removeClass("expanded").addClass("notExpanded");
	$("#collapseForForms").removeClass("expanded").addClass("notExpanded");
	$("#collapseForCustomized").removeClass("expanded").addClass("notExpanded");
	$("#collapseOne").removeClass("expanded").addClass("notExpanded");
	intialize();
	frmID="";
	data=[];
	helpdesc="";
	ruleOrder=0;
	innerFlagEdit = 0;
	imageNumber=0;
	stepNameFlag=0;
	sectionNameFlag=0;
	deleteFormImageFlag=0;
	deleteSectionImageFlag=0;
	deleteFormImage=[];
	deleteSectionImage=[];
	deleteStepImage=[];
	deleteStepImageFlag=0;
	deleteQuesImage=[];
	deleteQuesImageFlag=0;
	seqNoFormImages = 0;
	seqNoSectionImages =0;
	seqNoStepImages=0;
	seqNoQuestionImages=0;
	labelEditFormFlag=0;
	labelEditSectionArr=[];
	labelEditStepArr=[];
	labelEditQuesArr=[];
	clickedRow=""; desc=""; 
	tag=""; 	showDivFLag=0;
	actionID_num=""; 
	action=""; questArr=[];
	tagValue=""; sectionObj=[];
	opVal=""; stepArr=[];
	fields=""; stepsArr=[];
	output=""; stepCount_=0;
	innerID = 0;
	actionRulesArr =[];eleOrder=1;
	stepCount=0;
	label=[];
	quesText=0;
	countQuesImg = 0;sectionArr=[];
	quesArr=[];stepArr=[];secArr=[];formArr=[];quesText = 0;eleOredr=1;questionChange=[];
	actionRulesArr=[];ruleMainArr=[];
	quesCountNumber=0;
	quesCountNumber_=0;
	countSect=0;
	textAreaJsonArr=[];
	textAreaCount_=0;
	textAreacount=0;
	textCountArr=[];
	textArea_Count=[];
	dropDownCount_=0;
	dropDownJsonArr = [];
	dropDown_Count=[];
	dropDownCount=0;
	dropCountArr=[];
	datePickerCount_=0;
	datePickerJsonArr =[];
	datePicker_Count=[];
	datePickerCount=0;
	dateCountArr=[];
	btnCount_=0;
	buttonJsonArr =[];
	btn_Count= [];
	buttonCount=0;
	btnCountArr=[];
	addImageCount_=0;
	addImageJsonArr = [];
	addImage_Count=[];
	addIm=0;
	addimCountArr=[];
	checkboxCount_=0;
	checkBoxJsonArr =[];
	chk_Count=[];
	checkBoxCount=0;
	checkCountArr=[];
	radioCount_=0;
	radioButtonJsonArr=[];
	radio_Count=[];
	radioButton=0;
	radioCountArr=[];
	textboxCount_=0;
	textBoxJsonArr=[];
	textbox_Count=[];
	textBoxCount=0;
	textBoxCountArr=[];
	sigCount_=0;
	signatureJsonArr=[];
	sig_Count=[];
	signatureCount=0;
	sigCountArr=[];
	labelCount_=0;
	labelJsonArr=[];
	label_Count=[];
	labelCount=0;
	labelCountArr=[];
	imageUploadCount_=0;
	imageUploadJsonArr=[];
	imageUpload_Count=[];
	imageUploadCount=0;
	imuploadCountArr=[];
	ansIDCount=0;
	stepCount_=0;
	sect_Count=0;
}